# make everything show verbose messages
verbose = false

# prettify any text output file (such as atlas data json files)
prettify = false

[output]
# display output related verbose messages
verbose = false

# generated files name
name = "atlas"

# where to output generated files
path = "output"

[cache]
# display cache related verbose messages
verbose = false

# where cache files should be stored (leave empty to use system's default path)
path = ""

# which cache identifier to use (leave empty to generate a new one automatically)
identifier = ""

[packer]
# display packer related verbose messages
verbose = false

# atlas target size (width and height will be the same)
# accept any value, but a power of two is better
atlas_size = 1024

# should try to optimize packer values?
#   * use next (from atlas_size value) power of two atlas size
optimize = true

# force packing (or only do when it is needed)
force = false

[packer.retry]
# packer should retry when failed? (by lacking of space)
enable = true

# max retries (zero will make it retry indefinitely)
max_retries = 0

# retry until reaches an atlas size (zero will leave it to use default value, which is 4096)
until_atlas_size = 0

[image]
# display image related verbose messages
verbose = false

# where to get source images
input_path = "source"

# kind of image processing progress display, it could be: simple, list or detailed
display = "simple"

[image.aseprite]
# display aseprite's image related verbose messages
verbose = false

[data]
# display data related verbose messages
verbose = false

# prettify output data file
prettify = false
