name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    paths-ignore:
      - '*.md'

jobs:
  check:
    uses: lucas-miranda/clymene/.github/workflows/clippy.yml@main

  build:
    needs: check
    uses: lucas-miranda/clymene/.github/workflows/build.yml@main
